global:
  scrape_interval: 25s
  scrape_timeout: 20s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cassandra' 
    static_configs:
      - targets: ['cassandra-exporter-custom:8080']
