global:
  scrape_interval: 60s
  scrape_timeout: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cassandra' 
    static_configs:
      - targets: ['cassandra-exporter-custom:9100', 'cassandra-exporter-instaclustr:9500']
